services:
  runners-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: runners-app:latest
    ports:
      - "8080:8080"  
    networks:
      - marathon-net
networks:
  marathon-net:
    driver: bridge